name: Docker Image build

on:
  push:
  pull_request:

env:
  SHOULD_PUBLISH: ${{ startsWith(github.ref, 'refs/tags/') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Docker Tags
        id: meta
        uses: docker/metadata-action@v5
        env:
          semver: type=semver,value=${{ github.ref_name }}
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ env.semver }},pattern=v{{version}}
            ${{ env.semver }},pattern=v{{major}}.{{minor}}
            ${{ env.semver }},pattern=v{{major}}

      - name: Login to GHCR
        if: env.SHOULD_PUBLISH == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.SHOULD_PUBLISH == 'true' }}
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Added to prevent tons of untagged images in GHCR.
          # See: https://github.com/docker/build-push-action/issues/894
          provenance: false
